version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network

  uvicorn:
    image: python:3.10.11-slim
    build: .
    volumes:
      - .:/app
    command: uvicorn app.asgi:application --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uvicorn
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
