version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network
    command: uvicorn app.asgi:application --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
