services:
  web:
    build: .
    # command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    environment:
      - DOCKER=1
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
